name: vmsg-data-vis
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab>=3.0
  - pandas-datareader>=0.5.0
  - matplotlib>=3.2.2
  - ipywidgets
  - jupyter_contrib_nbextensions
  - IPython.display
  - pip
  - pip:
numpy
matplotlib
pandas
scikit-learn
